### ISSUE TITLE
`vpc_zone_identifier`: should be a list

### ISSUE THREAD

**Issue by guilhermeblanco** [scholzj/terraform-aws-kubernetes#1]
When attempting to use the output of a counted resource into the module, it throws the error that vpc_zone_identifier should be a list. Example:

```
module "kubernetes" {
  source = "scholzj/kubernetes/aws"

  master_subnet_id = "${element(aws_subnet.public.*.id, 0)}"
  worker_subnet_ids = "${aws_subnet.protected.*.id}"

  # ...
}
```

**Comment by scholzj** [comment]
Thanks for raising this issue. It should be fixed now in release 1.1.1. Please give it a try. I will close this issue now - if you still experience some problems please feel free to reopen it.
