### ISSUE TITLE
Install script didn't run?

### ISSUE THREAD

**Issue by webchi** [scholzj/terraform-aws-kubernetes#18]
Hi! I used your module but after terrfaorm apply I have clear master instance on EC2. Even no epel-release have installed. 
What it could be?

**Comment by webchi** [comment]
Need run `terrform apply` twice

**Comment by scholzj** [comment]
I'm sorry I didn't got to this yesterday. I was busy with something else. However, I tried it today and it worked fine for me. So maybe it was just some glitch or something like that.
