### ISSUE TITLE
Error: Attribute redefined - The argument "tags" was already set

### ISSUE THREAD

**Issue by cmrust** [scholzj/terraform-aws-kubernetes#26]
I'm receiving the following error on module version 1.6.1:

```
Error: Attribute redefined

  on .terraform/modules/kubernetes/scholzj-terraform-aws-kubernetes-6fb01f4/main.tf line 371, in resource "aws_autoscaling_group" "nodes":
 371:   tags = [{

The argument "tags" was already set at
.terraform/modules/kubernetes/scholzj-terraform-aws-kubernetes-6fb01f4/main.tf:365,3-7.
Each argument may be set only once.


Error: Attribute redefined

  on .terraform/modules/kubernetes/scholzj-terraform-aws-kubernetes-6fb01f4/main.tf line 377, in resource "aws_autoscaling_group" "nodes":
 377:   tags = ["${var.tags2}"]

The argument "tags" was already set at
.terraform/modules/kubernetes/scholzj-terraform-aws-kubernetes-6fb01f4/main.tf:365,3-7.
Each argument may be set only once.
```

It seems the tags attribute shouldn't be redeclared over and over here:

https://github.com/scholzj/terraform-aws-kubernetes/blob/7e4342ca7491cff178c8f265bef0f5d8d7639ba9/main.tf#L356-L382

**Comment by scholzj** [comment]
This seems to work fine for me with Terraform 0.11.11. What version of Terraform are you using?

**Comment by cmrust** [comment]
Hey @scholzj. Yep, looks like this error is specific to 0.12.0, which was just released. Rolled back to 0.11.14 and it's working fine again. To clarify above, this error was generated during a `terraform init`.

**Comment by scholzj** [comment]
Hmm, I will have a look if there is some workaround.

**Comment by Ph3nol** [comment]
Any clue about it? Thank you.

**Comment by scholzj** [comment]
FYI: I'm thinking about moving to Terraform 0.12.0 from Kubernetes 1.15. So that should be the timeframe I will look at this.

**Comment by scholzj** [comment]
@cmrust I finally found some time to upgrade to Kubernetes 1.15.x and Terraform 0.12.x. Please give try to the last release.
