### ISSUE TITLE
Can I chose the kubernetes version ?

### ISSUE THREAD

**Issue by leonrado** [scholzj/terraform-aws-kubernetes#28]
I like to choose to install kubernetes 1.15....there is some easy for this ?

**Comment by scholzj** [comment]
I use this mainly for development - so I always have only the (more-or-less) latest Kubernetes versions and don't have any way to select older Kubernetes version. But you can always checkout an older version from GitHub which was based on older Kubernetes version and use it. For example 1.7.2 (GitHub tag `v1.7.2`) was based on 1.15.3.

**Comment by leonrado** [comment]
> I use this mainly for development - so I always have only the (more-or-less) latest Kubernetes versions and don't have any way to select older Kubernetes version. But you can always checkout an older version from GitHub which was based on older Kubernetes version and use it. For example 1.7.2 (GitHub tag `v1.7.2`) was based on 1.15.3.

I'm understood. Thank you.
