### ISSUE TITLE
private subnet

### ISSUE THREAD

**Issue by leonrado** [scholzj/terraform-aws-kubernetes#29]
There is some easy way to deploy the cluster in a private subnet ?

**Comment by scholzj** [comment]
TBH, I do not have any environment with private subnets to test it right now. Long time ago it did work out of the box since I used it with private subnets, but I might have done some changes which break that TBH. Did you tried it and run into any particular issue?

**Comment by leonrado** [comment]
> TBH, I do not have any environment with private subnets to test it right now. Long time ago it did work out of the box since I used it with private subnets, but I might have done some changes which break that TBH. Did you tried it and run into any particular issue?

Thank you for your message !

What's I really mans to said is that the workers receive a public IP although variable public_worker is false.
I just test it right now

**Comment by leonrado** [comment]
This is working pretty well. My bad sorry.
And congratulation for this project.
