### ISSUE TITLE
Scaling down fails due to missing permission

### ISSUE THREAD

**Issue by Kazetsukai** [scholzj/terraform-aws-kubernetes#9]
It seems that Kubernetes is failing to scale down an autoscaling group. The permission I could see that it seems to be missing is `autoscaling:DescribeLaunchConfigurations`. Not sure if it needs more than just that one.

**Comment by scholzj** [comment]
Thanks for raising this. 

I added `autoscaling:DescribeLaunchConfigurations` to the master IAM role. But I think that should not be needed in all cases. But it seems there were some things missing in the RBAC rights on Kubernetes level. I fixed that and now it seems to work for me. Please give it a try.

**Comment by Kazetsukai** [comment]
Thanks for that, going to give it a shot.
